# exit_engine/contracts.py
# ========================
# Phase‑9C : Multi‑Timeframe Exit Engine Contracts
# Institutional‑Grade | Immutable | Side‑Effect‑Free

from enum import Enum
from dataclasses import dataclass


# ---------------------------------------------------------------------------
# Exit Signal Types (Generated by Higher‑TF Detectors – e.g. M15)
# ---------------------------------------------------------------------------

class ExitSignalType(Enum):
    NONE = "none"                # No structural exit signal
    WEAKENING = "weakening"      # Trend is losing strength
    REVERSAL = "reversal"        # Confirmed trend reversal
    DISTRIBUTION = "distribution"  # Smart‑money exit / absorption


# ---------------------------------------------------------------------------
# Exit Severity (Decided by Mid‑TF Confirmation – e.g. M5)
# ---------------------------------------------------------------------------

class ExitSeverity(Enum):
    HOLD = "hold"        # Do nothing
    PARTIAL = "partial"  # Scale‑out
    FULL = "full"        # Close entire position


# ---------------------------------------------------------------------------
# M15 : Exit Warning (No Execution – Advisory Only)
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ExitWarning:
    """
    High‑timeframe exit warning.
    This object never triggers execution by itself.
    """
    active: bool
    signal_type: ExitSignalType
    confidence: float           # 0.0 ... 1.0
    reason: str


# ---------------------------------------------------------------------------
# M5 : Exit Confirmation (Severity Decision)
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ExitConfirmation:
    """
    Mid‑timeframe confirmation layer.
    Confirms or rejects an ExitWarning and assigns severity.
    """
    confirmed: bool
    severity: ExitSeverity
    reason: str


# ---------------------------------------------------------------------------
# M1 : Exit Action (Execution Instruction)
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ExitAction:
    """
    Final execution instruction.
    Consumed directly by ExecutionPolicy / OrderExecutor.
    """
    close: bool                  # True -> send close / reduce order
    close_ratio: float           # 0.0 ... 1.0 (1.0 = full close)
    reason: str


# ---------------------------------------------------------------------------
# Exit Context (Position‑Only State – No Market Data)
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ExitContext:
    """
    Immutable snapshot of the open position.
    Provided by the Orchestrator.
    """
    symbol: str
    side: str                    # "LONG" | "SHORT"
    entry_price: float
    size: float
    unrealized_pnl: float
    open_time: float
